### ISSUE TITLE
Baseurl should be empty on root

### ISSUE THREAD

**Issue by thde** [poole/lanyon#101]
The baseurl is currently configured as `/` if you use the theme on the root path. In my opinion it sould be empty. Because right now, the "related posts" links will produce  `<a href="//example-post/">` from `<a href="{{ site.baseurl }}{{ post.url }}">`. 

As described in Parkers [blogpost](https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/). =)

**Comment by mdo** [comment]
Address in #102.
