### ISSUE TITLE
Excerpts on the home page?

### ISSUE THREAD

**Issue by Siyfion** [poole/lanyon#113]
I'm probably just being a complete noob here, but I can't seem to get excerpts working no matter what I try. I'm (ideally) looking to have the last 10 posts listed on the home page, each with a small excerpt to make it nicely readable.

But I've tried changing the `index.html` to display `post.excerpt` and it didn't seem to have an effect!?

**Comment by nicolasmccurdy** [comment]
Do you have a repository we can look at?

**Comment by Siyfion** [comment]
@nicolasmccurdy Not a "broken" one, but I thought it would be a simple case of changing https://github.com/poole/lanyon/blob/master/index.html#L17 to be `{{ post.excerpt }}`??

**Comment by Siyfion** [comment]
@mdo & @nicolasmccurdy  Is that not what I should have done?

**Comment by 1nsunym** [comment]
Any progress on getting it to work? Mine doesn't work either

**Comment by wireddown** [comment]
@Siyfion, what is your [`excerpt_separator`](http://jekyllrb.com/docs/posts/#post-excerpts) ?

**Comment by 1nsunym** [comment]
Mine got fixed. I was dumb enough to not notice a whitespace in my _excerpt_serpator_
