### ISSUE TITLE
site.github.repo variable not in _config.yml

### ISSUE THREAD

**Issue by jholl** [poole/lanyon#118]
`{{ site.github.repo }}` is in the sidebar.html include but not the config.  It does exist in the config for poole and hyde.  Seeing as this is much a starting place, it's not hard to add/remove either way, but in case it was not intended...

**Comment by nicolasmccurdy** [comment]
It seems like this is an intentional usage of [repository metadata on GitHub Pages](https://help.github.com/articles/repository-metadata-on-github-pages/).

**Comment by jholl** [comment]
that's fantastic!  I stepped away from gh-pages for a while, so forgive me while I "get with the program."
