### ISSUE TITLE
 Layout mode in iPhone 6 not rendering properly

### ISSUE THREAD

**Issue by miguelmcolon** [poole/lanyon#119]
This is an issue in layout mode on certain devices:
I don't know exactly where the problem is (maybe an @media and rem issue) but the site is not rendering properly when using an iPhone 6 in layout mode (Safari and Chrome for iOS tested). Not tested in other devices except iPad 2, where it seems to render perfectly.

The effect is that the site is switching between one size and another making it useless in Layout mode in iPhone 6.

**Comment by jvcasill** [comment]
I noticed this as well. I switched the fonts (site-wide) and it went away.

**Comment by miguelmcolon** [comment]
Hi @jvcasill! 
Would you mind giving me more information about how you switched the fonts (file, line, etc...)?
Thanks in advance

**Comment by jvcasill** [comment]
Hi @miguelmcolon ,
I did this awhile ago, so I don't remember the specifics, but I know I went here:

    libraries > frameworks > lanyon > partials > head.html

and I took out whatever stylesheet link was there (for the fonts), and replaced it with this one:
 
      <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Maven+Pro">

Hopefully that works for you.

**Comment by miguelmcolon** [comment]
Hi again @jvcasill, 

It doesn't work for me. I'll continue playing with CSS files...

Thank you a lot!

**Comment by jvcasill** [comment]
@miguelmcolon I'm sorry to hear that. I will try and take a look this afternoon and see if I can give you any more details.

**Comment by aldanor** [comment]
On iPhone 6 in layout more, the sidebar button overlays the content in a very ugly way and always stays in top left corner no matter how far down you scroll :/

**Comment by hbahamonde** [comment]
Hi @miguelmcolon and @jvcasill, I was wondering if you could share how one can change the fonts. I checked elsewhere but didn't find anything - I'm kind of new here, so any hint is appreciated it. Cheers!

**Comment by miguelmcolon** [comment]
Hi @hbahamonde, User @jvcasill explains how to change fonts references links in his comment on Jun 22. You should check every file with reference links for the fonts and change these links.
Hope it works.

**Comment by hbahamonde** [comment]
Thanks @miguelmcolon for your answer. Yes, I figured it out later that day, and it worked. I'm still very new to this, so thanks for your answer again!

**Comment by mdo** [comment]
Likely the sa,e issue as #164—the rem units in media queries are causing the funkiness.
