### ISSUE TITLE
Sidebar menu is not shown in the mobile mode

### ISSUE THREAD

**Issue by vitalyrepin** [poole/lanyon#123]
Hello,

I just have started to use lanyon for my blog.  If I open it with desktop browsers, everything is OK.

But if I open it with mobile phone (Android built-in browser), no side bar button is shown.

My site: vrepin.org  Sources: https://github.com/vitalyrepin/vrepinblog

Any ideas what is wrong? 

Thanks in advance!

**Comment by ryano88** [comment]
I am running android 5.0.1 on my galaxy note 4 and I can see the sidebar button (which works correctly) on both the stock android browser and chrome

**Comment by vitalyrepin** [comment]
I use Android 4.1.2 

I've just checked it again - I can see it with Android Chrome browser but not with a built-in browser.

Another problem I have with mobile device is my addition to default.html:

```html
 <a href="{{ site.baseurl }}/" title="Home">{{ site.title }}</a>
 <small>
{% for page in site.pages_list %}
  &nbsp;&nbsp;&nbsp;
  <small><a href="{{ page[1]  }}">{{ page[0] }}</a></small>
{% endfor %}
</small>
</h3>	   
```

sites.pages_list are pages which are shown after the title of the bog (About, feed etc). They are shown nice in the desktop but are not shown in Android Chrome neither in Android built-in browser.

**Comment by mdo** [comment]
Closing because of age and how terrible Android’s old browser was :).
