### ISSUE TITLE
Not compatible with Jekyll 3.0

### ISSUE THREAD

**Issue by joacimmelin** [poole/lanyon#124]
Hi,

I get this error message when trying Lanyon with Jekyll-3.0.0.pre.beta8: 

"Since v3.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Check http://jekyllrb.com/docs/upgrading/ for more info."

Any plans to update this great theme for 3.0? 

Thanks,

Joacim

**Comment by nicolasmccurdy** [comment]
:+1: for working on support for this. Is Poole itself ready for Jekyll 3.0? If not, should that happen first?

**Comment by joacimmelin** [comment]
Any news on this?  I still can't build my Lanyon based site with Jekyll 3.0.0.pre.beta8.

**Comment by heathyates** [comment]
I did some googling and found some things that might help you. I needed to make two changes to _config.yml to get it to work. 

Change 1: 
  `gems:                [jekyll-paginate]
  paginate:            5
  paginate_path:       "page:num"`

Change 2: 
Remove `relative_permalinks: true`

If you want I can make a pull request to Lanyon if this works for everyone.

**Comment by patrickhempel** [comment]
Unfortunately, it dosen't work for me.
jekyll creates odd urls for all the posts on the index page.
The url for the first post was generated as http://0.0.7.222/01/02/introducing-lanyon.html.

I use jekyll 3.0.0 with ruby 2.1.4p265 on Mac OS 10.11.1

Any idea how to solve this?

Greetings, Patrick

**Comment by ravicious** [comment]
See [#108](https://github.com/poole/lanyon/issues/108#issuecomment-104944040).

**Comment by patrickhempel** [comment]
Thank you. 
Everything is working now as expected. 
I totally overlooked issue #108

**Comment by akaak** [comment]
It works for me as well after I made the two changes that were mentioned above by @heathyates.

**Comment by tgharib** [comment]
I can confirm that heathyates's two changes worked.

**Comment by rfelten** [comment]
thx @heathyates

**Comment by Ralphilius** [comment]
Changes suggested by @heathyates work for me :)
Thanks.

**Comment by Hany3ssam** [comment]
@heathyates Thank You, That Worked

**Comment by IanJang** [comment]
@heathyates  Thanks a lot. I could build a jekyll templete because of your reply.

**Comment by keeprock** [comment]
@heathyates you're the man!
