### ISSUE TITLE
Suggestion: New Sidebar

### ISSUE THREAD

**Issue by nicholaelaw** [poole/lanyon#138]
Don't know if this is relevant, but I think I've found a better sidebar implementation.

I've recently replaced the default sidebar with [eager-side-nav](https://github.com/EagerApps/SideNav) and found the result good enough. It uses almost solely js to make the sidebar, and has a nice animated button.

You can preview the effects at [its eager.io install page](https://eager.io/app/sidenav/install).

Right now it's a standalone package with some basic options. If properly integrated the side nav should support Lanyon color theming and also `reverse-layout` and `sidebar-overlay` options. I've only been able to make a few hacks to place it to the right (like reverse-layout) and change the color to #AC4142 (theme-base-08). I'll try to integrate it, but anyone more capable than I are more than welcome to do it.

**Comment by mafagafogigante** [comment]
> better sidebar implementation

Can you please elaborate?

> nice animated button

This is not enough to make it any **better**. It is different and no more than that. Also, I think it does not blend well with Lanyon.

**Comment by nicholaelaw** [comment]
I'm sorry I shouldn't have said "better". I should have said "I like it better". Some highlights are:

1. It allows multiple sections in sidebar (labels that separates groups of link);
2. I've had a problem I can't fix with Lanyon's sidebar: [Issue 137](https://github.com/poole/lanyon/issues/137), this implementation behaves fine;
3. The **nice** animated toggle has a fixed position. In some use cases, this reduces mouse/finger travel;
4. Built-in icon support which does not require any additional setup.

I also recognize some shortfalls:

1. It is written in JS+JSON, which could raise compatibility issues;
2. On narrower screens the toggle button overlays on texts;
3. It needs to be loaded in HTML `head`: if loaded in `body`, the toggle appears halfway through page loading, which can be perceived as poor performance;
4. It behaves like Lanyon's `sidebar-overlay`, which conflicts with current sidebar's default behaviour.

Lastly, I'm afraid I disagree with your assessment that it does not blend well with Lanyon. Here's Lanyon's sidebar (:

<img width="492" alt="lanyon-sidebar" src="https://cloud.githubusercontent.com/assets/10719482/9940175/c1991fc8-5da0-11e5-9d37-863e5561488d.png">

and here's eager-side-nav modified by me:

<img width="439" alt="side-nav-adapted" src="https://cloud.githubusercontent.com/assets/10719482/9940200/dfce097c-5da0-11e5-8cfa-343db99051bb.png">

Aside from the narrower width and different text position, I couldn't see why it does not blend well with Lanyon.

**Comment by mafagafogigante** [comment]
I think I even like it better after seeing this images. I didn't experiment with it enough to make it blend in properly. I have nothing else to say, if performance and compatibility are minor issues I'm likely going to use this in my own website. Can't say I think it is a good idea to make it Lanyon's default, though.
