### ISSUE TITLE
Removing 'Download' & 'Github Project' pages

### ISSUE THREAD

**Issue by SurAnand** [poole/lanyon#143]
Hi, thanks a lot for this template. I loved it instantly and I now run my own page here at http://suranand.github.io/

- However, as I am not a web developer, I have done things simply by using my intuition in copying and modifying the required files for this entire site to work. But I am stuck on how to get rid of "Download" and "Github Project" pages from the side bar. 
- In place of them, what if I just want to create a 'page' in a way that by clicking on the page name from side bar should redirect me to my twitter page.

Please help me with these 2 steps.
Thanks
Anand

**Comment by SurAnand** [comment]
I just solved this problem by looking at your `sidebar.html`. I got another issue though. Will close this one and open a new issue for that. Thanks.

**Comment by marcomangiante** [comment]
Sincerely, the problem that I found, for example for 'GitHub Project', is that {{ site.github.repo }} point, for a repository like username.github.io, to this and not to GitHub.com/username/username.github.io; while  {{ site.github.repo }} works well for project repository, it doesn't work for personal or company repository.
