### ISSUE TITLE
Clicking anywhere closes sidebar

### ISSUE THREAD

**Issue by lowrie** [poole/lanyon#162]
This is a great theme, but I'm having a small issue.  I'm using Jekyll 3.0, because I'd like to use this theme with github.  When I build this repo (with the minor fixes required for 3.0 discussed here), or when I build the fork https://github.com/xHN35RQ/lanyon (no fixes required), the sidebar closes when I click **anywhere** in the window, instead of just when clicking on the hamburger.  I don't have this issue with  the site http://lanyon.getpoole.com/.  Any idea how to fix this?

**Comment by xHN35RQ** [comment]
This is a feature that was added to lanyon to support mobile touch screens. The feature was added in response to issue #42. The specific commit is https://github.com/poole/lanyon/commit/09dfba154af68e0d89369445297888bb78631c06 and adds a bit of javascript to the bottom of the `default.html` layout. In my fork, I've moved the javascript to it's own file: https://github.com/xHN35RQ/lanyon/commit/8e3ba600ee04d99801479b6f68499f9a772183fd

So you can remove this javascript, and the site will revert back to only toggling the sidebar when you click/touch the sidebar button.

However on mobile, if you have a long side bar, and you open the sidebar, then scroll down the page, you won't be able to close the sidebar unless you scroll back up and touch the button again. So perhaps you might consider only including this javascript for mobile devices, and not include it on desktop browsers.

Hope that helps.

**Comment by mafagafogigante** [comment]
Slightly OT, https://github.com/xHN35RQ/lanyon/commit/8e3ba600ee04d99801479b6f68499f9a772183fd and https://github.com/xHN35RQ/lanyon/commit/91ff4720ec4b0680b140fe73d5ae5aaae22905a2 should be a single commit for consistency purposes.

Moving JS to a dedicated file is a nice thing to do though (organization-wise).

**Comment by xHN35RQ** [comment]
You're right. I need to work on making my commit history less haphazard.

**Comment by mafagafogigante** [comment]
Glad you weren't bothered by it. I just like to think that we can build a better generation of programmers by pointing out small things like these. I went there to see if I could cherry pick a commit to "fix" this for me.

**Comment by xHN35RQ** [comment]
Right on! And when I'm finished refactoring my fork, I'll link the commit for you.

**Comment by xHN35RQ** [comment]
@mafagafogigante here's the commit: https://github.com/xHN35RQ/lanyon/commit/de3dd74293c7d3b8a90214cb886772a0b0adb82a

**Comment by lowrie** [comment]
@xHN35RQ Thanks, that helps and makes sense.

**Comment by xHN35RQ** [comment]
Just a note: I have now reverted that commit and have re-included the javascript in the page template. Google Page Speed Insights recommends inclining small bits of javascript instead of adding an extra external http call by sourcing them.
