### ISSUE TITLE
Error in relative_permalinks building on Github Pages

### ISSUE THREAD

**Issue by tomsarduy** [poole/lanyon#174]
There is an error, I think because Github pages is using Jekyll 3, and `relative_permalinks` is deprecated. The issue can be solved removing `relative_permalinks` from `_config.yml`, but not sure if it will have more implications.

**Comment by mafagafogigante** [comment]
Next time do some searches before creating an issue. [See the original issue](https://github.com/poole/lanyon/issues/124).

**Comment by tomsarduy** [comment]
@mafagafogigante my bad, still not fixed?

**Comment by jhabdas** [comment]
@tomsarduy this is a duplicate. please close
