### ISSUE TITLE
sidebar-overlay OK but can not click nav-items

### ISSUE THREAD

**Issue by srlopez** [poole/lanyon#176]
Aftr installing the piece for sidebar-overlay, can not click on items in the navigation bar.
If i remove the sidebar-overlay from <body class="theme-base-00 sidebar-overlay"> any things again is right!

I cannot resolve this question.
May you help me?
Thanks

**Comment by mdo** [comment]
I can’t reproduce this issue at this time, perhaps the four years of radio silence from me fixed it 😅
