### ISSUE TITLE
How to reset the number of commits and collaborators?

### ISSUE THREAD

**Issue by jroberayalas** [poole/lanyon#179]
Hi! If I fork this repo to use it as a baseline for my own website, is it possible to clear the number of commits and collaborators (and set the later to 1)?

Thanks!

**Comment by mafagafogigante** [comment]
I don't think so. If I recall correctly, the number of collaborators is derived from commit authors. You could perform a shallow clone locally, amend the last commit with yourself as the author, and continue from there.

This would be a 1 commit from 1 author here.

**Comment by jackwilsdon** [comment]
You could try the following:

 1. Fork and clone the repository.

    ```shell
    git clone git@github.com:your-username/lanyon.git
    ```

 2. Nuke the history of the repository.

    ```shell
    rm -rf .git
    git init
    ```

 3. Add an initial commit.

    ```shell
    git add .
    git commit -m "Fork from pooly/lanyon#ac85a31"
    ```

The main issue with doing this is that you'll lose the ability to easily merge any changes made here back into your repository (i.e. fixes or updates to the theme).

Is there a reason you're looking to do this?

**Comment by jroberayalas** [comment]
@jackwilsdon not really, I was just thinking that it seems a bit weird to have a "personal" website with 18 contributors. Not sure if the idea suggested by @mafagafogigante could work better.

**Comment by mafagafogigante** [comment]
It isn't weird. It has 18 contributors as the theme isn't the gift of a deity but a collaborative work and acknowledging that seems a perfectly reasonable.

I would rather do it my way (if I was going to do it at all). However, I think both will leave you with roughly the same result for all practical purposes.
