### ISSUE TITLE
needs update?

### ISSUE THREAD

**Issue by sigul** [poole/lanyon#197]
HI, i am trying to run it locally, I downloaded the zip, unzipped, gem install jekyll pygments.rb and I got this error

      Generating... 
Since v3.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Check https://jekyllrb.com/docs/upgrading/ for more info.

**Comment by susodapop** [comment]
To fix this, remove the following from `_config.yml`.

    relative_permalinks: true

You also need to add the line:

    gems:
        [jekyll-paginate]

Otherwise the blog entries will not appear unless you navigate to them directly.

**Comment by cmartinaud** [comment]
I have done both things and the entries still does not appear. What can I do?
