### ISSUE TITLE
how to assign each post its own page

### ISSUE THREAD

**Issue by kapilkd13** [poole/lanyon#202]
Hi all, This is more of a doubt than a issue. I am new to Jekyll. I liked lanyon and built it on my local system. My problem is, there are 3 posts in `_posts` folder but they all appear on the same page(Home). what I want is that each post should have its own page later I will be putting disqus comment section under each page. Is there a way that I only get small description of all posts on home page and on clicking it, I get redirected to that particular post's page. how can I do it.

**Comment by mdo** [comment]
You’ll have to modify the theme to do that. Read up on Jekyll’s docs for loops, excerpts or other page front matter, and pagination.
