### ISSUE TITLE
CSS not rendering on all pages - Github only

### ISSUE THREAD

**Issue by eaglerockdude** [poole/lanyon#206]
I added a few pages..not on github I can see the .css files(all) are not being found(status 404)...it only loads them on the first(home page)...

I did make some updates(pygments to rouge and redcarpet to kramdown but I don't think that caused it..it happend all of a sudden after that though.

I don't know if this is an issue..just a general question..any ideas?  Should i restore back to a version that was working...

**Comment by lancelote** [comment]
Same problem for me.

**Comment by stephendrew** [comment]
Also have this....  had to disable relative_permalinks to get github to build it
