### ISSUE TITLE
No page style

### ISSUE THREAD

**Issue by alwynmathew** [poole/lanyon#225]
Direct fork, with few change: I renamed the `CNAME` file to `CNAME.sample` and changed `baseurl` to  `/lanyon/`. Still, no styling appears when I goto the site. Here is the [site](https://alwynmathew.github.io/lanyon/), here is the [repo](https://github.com/alwynmathew/lanyon). Thanks for your help!

**Comment by jackwilsdon** [comment]
Looks like `baseurl` isn't pulling through correctly, as [head.html](https://github.com/poole/lanyon/blob/master/_includes/head.html) uses it to build the CSS URLs. Not quite sure why this is happening though.

**Comment by alwynmathew** [comment]
According to [this](https://github.com/poole/poole#4-serving-it-up) I tried changing `baseurl` to `http://alwynmathew.github.io/lanyon/` but didn't help.
