### ISSUE TITLE
Wishlist branch with fixes and features

### ISSUE THREAD

**Issue by wireddown** [poole/lanyon#226]
Hi Lanyon fans!

I love and use Lanyon for my GitHub Pages sites. Because this repo has been still for a little while, I created a branch called [`upstream-wishlist`](https://github.com/wireddown/wireddown.github.io/tree/upstream-wishlist#setup) that includes some fixes and features. You're welcome to clone/fork it for your own use, too!

https://github.com/wireddown/wireddown.github.io/tree/upstream-wishlist

# Changes from `HEAD`

- Fix intra-site links
    - #108, #140, #180, #206, #209, #210, #225
- Compatible with Jekyll 3
    - #124, #197
- Added search page
    - #194
- Added support for tags
    - #83

**Comment by mdo** [comment]
Thanks for having done this! Working on getting caught up.
