### ISSUE TITLE
How to keep my changes to index.html after running jekyll serve

### ISSUE THREAD

**Issue by phosseini** [poole/lanyon#229]
I know that this issue is not necessarily specific to the lanyon, but since I could not find my answer I'm asking this here. Issue is simple, I want to modify the `index.html` file. I know that if I make the changes to the index.html in `_site` folder, after running the `jekyll serve` command the folder content will be overwritten and everything in _site backs to the default. What should I do to keep my changes even after running the `jekyll serve` command then? I read somewhere that I need to put my file into the _layout folder (anywhere other than _site) which I did but that does not work either.

**Comment by mdo** [comment]
Don’t modify the content in `_site`—you need to modify the source files. Find the `index.html` in the root instead.
