### ISSUE TITLE
adding vertical hyperlinks in sidebar 

### ISSUE THREAD

**Issue by Arconapalus** [poole/lanyon#231]
I'm looking to add hyperlinks to the sidebar which, I was able to do. However, the links are horizontal and I'm looking to make them vertical. I configured the sidebox-item for example to display: block; and nothing happens. Is there a way to add hyperlinks and make them vertical?

**Comment by mdo** [comment]
Not sure what this means, please file a new with screenshots or more context if this is still a problem.
