### ISSUE TITLE
Host on GitHub pages

### ISSUE THREAD

**Issue by stefanbschneider** [poole/lanyon#237]
I'd like to build and host lanyon on GitHub pages. Is that possible? If so how? I couldn't find any documentation on this.

If I just fork and build the pages based on the `gh-pages` branch, the resulting page is plain HTML and looks horrible: https://stefanbschneider.github.io/lanyon/
Using `master` doesn't work at all and the build fails.

The changes suggested [here](https://github.com/poole/lanyon/issues/124#issuecomment-155645090) seem not to apply to the current config in `gh-pages`.

**Comment by stefanbschneider** [comment]
Sorry, I found my answer here: https://github.com/poole/poole#usage

**Comment by stefanbschneider** [comment]
Actually, not solved afterall.

My page still looks like this: 
![grafik](https://user-images.githubusercontent.com/28340802/76652686-62b09d00-6567-11ea-8784-269f54e7b654.png)

Wether I'm serving from `gh-pages` or `master` branch. I adjusted the baseurl, repo, and relative links in the config.

**Comment by stefanbschneider** [comment]
Hm, if I run it locally with `baseurl = ''` from `master` it looks good. But I can't get it to work as GitHub pages project page.

Which branch do I need to use? How do I set `baseurl`, `url`, `repo`?

**Comment by nan-af** [comment]
One way I got it to work, is by copying the ```public``` folder to the root of my repository

**Comment by Zju-George** [comment]
1.Delete line https://github.com/poole/lanyon/blob/ac85a3115c094b3e6cb92cc41771e98b443f6c5d/_config.yml#L5
2.Change ur repo name to "stefanbschnider.github.io", then `url:                 "https://stefanbschnider.github.io"`.

**Comment by stefanbschneider** [comment]
@Zju-George That's what I already have: https://github.com/stefanbschneider/lanyon/blob/gh-pages/_config.yml

Why would I set the the repo to `stefanbschnider.github.io`? The repo is `https://github.com/stefanbschneider/lanyon`. Note: I'm trying to make a project page at `stefanbschnider.github.io/lanyon`, not my personal main page.

**Comment by mdo** [comment]
The stylesheets are missing a `baseurl` or equivalent change to always work regardless of deployment. Sorry about that, lemme see what I can clean up.

**Comment by mdo** [comment]
Latest release should help—make sure your `url` is set correctly and Jekyll should cover the rest now. Going to see if I can improve things further in v1.2.0.
