### ISSUE TITLE
Display posts title and meta only on the home page

### ISSUE THREAD

**Issue by hash-ir** [poole/lanyon#248]
I have little to no experience in web design. I want to know how can I change the default layout to lists all of the posts on the home page perhaps with a short description without their full content. Something like [this](https://drive.google.com/file/d/1c3hl401pIpFDb2Oqz-zu3MBfLyncZPoc/view?usp=sharing).
I suppose it has something to do with changing `{{ content }}` variable in `page.html` with `{{ description }}` and then replicating it in `index.html` as `{{ post.description }}`. But, I have no idea where the liquid variable `{{ description }}` will take its value from.

**Comment by hash-ir** [comment]
I found `{{ post.excerpt }}` and it does what I wanted. Thanks anyway!

**Comment by davidpasini** [comment]
> I found `{{ post.excerpt }}` and it does what I wanted. Thanks anyway!

@hash-ir I would like to implement this feature too. I tried to substitute {{ post.content }} with {{ post.excerpt }} in index.html but no luck.

Do you need to bring changes elsewhere or use a specific markup in the posts you write?

Tnx in advance,
d.

**Comment by hash-ir** [comment]
@davidpasini I saw that you closed the issue. Let me know if you still need help!
