### ISSUE TITLE
Style not rendered when hosting on Github Pages [#237]

### ISSUE THREAD

**Issue by I7T5** [poole/lanyon#309]
I'm still having [#237] issues : (. 

My [repo](https://github.com/I7T5/i7t5.github.io). It's the gh-pages branch. The main branch is minima. 

My problem
<img width="1440" alt="Screen Shot 2022-09-20 at 18 59 27" src="https://user-images.githubusercontent.com/105357663/191240960-2fb057a5-62c4-4a2e-a88a-3a0a52b98712.png">

My _config.yaml
```
# Setup
title:               From Ina
tagline:             ''
description:         'Hello, world! Welcome to my very first website : D'
url:                 http://i7t5.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ina Tang
  url:               https://github.com/I7T5
  email:             inatang75@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
google_analytics_id: #UA-XXXX-Y
```

Does it have to do with the absolute paths in head.html? (I'm new at all this, it's a random guess.)

Additional question: how do you add multiple lines in the description? I would like one line for each sentence.

**Comment by I7T5** [comment]
[get_a_pet_duck](https://www.reddit.com/user/get_a_pet_duck/) from reddit says this: 

Look at error being logged in your inspecto
```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure stylesheet '<URL>'. This request has been blocked; the content must be served over HTTPS.
```
I'm guessing it's this in atom.xml in root: 
```
<feed xmlns="http://www.w3.org/2005/Atom">
```

But I don't know how to solve this... @mdo

**Comment by I7T5** [comment]
Issue solved when I replaced the following 'absolute_url' to 'relative_url' in root/_includes/head.html

```
  <link rel="stylesheet" href="{{ '/public/css/poole.css' | absolute_url }}">
  <link rel="stylesheet" href="{{ '/public/css/syntax.css' | absolute_url }}">
  <link rel="stylesheet" href="{{ '/public/css/lanyon.css' | absolute_url }}">
```

But I don't understand why the favicons showed up fine with absolute_url 🤔

**Comment by heatforecast** [comment]
Had the same problem, solved it the same way, thanks!!
