### ISSUE TITLE
Sidebar toggle renders poorly with custom font-size

### ISSUE THREAD

**Issue by shiba89** [poole/lanyon#66]
I tried changing font-size in poole.css to different values, and the sidebar toggle doesn't look as good as when it is set to 20px. Here are some screenshots with font-size: 17px using different browsers:

Firefox
![ffox](http://i.imgur.com/9hml0MS.png)

Chrome
![chrome](http://i.imgur.com/cizsdqj.png)

Internet Explorer
![ie](http://i.imgur.com/6sDfCCr.png)

Safari
![safari](http://i.imgur.com/2EL4ASP.png)

**Comment by Mstaaravin** [comment]
Hey
You can resolve this...?
