### ISSUE TITLE
Weird flicker on Sidebar (Chrome/Safari)

### ISSUE THREAD

**Issue by ubersome** [poole/lanyon#78]
Appears to be a weird flicker on Chrome and Safari when using the sidebar toggle. When viewed on Chrome, the white flicker appears 100% of the height of the sidebar. In Safari, the flicker appears at the bottom. There doesn't appear to be any flicker in FF.

https://cloudup.com/cl_mOwWS6rQ

To recreate, simply apply a `background-color: ...;` to the `.masthead` class.

**Comment by mdo** [comment]
I see no flickering. Closing until I hear more with a reproducible test case.
