### ISSUE TITLE
Background color (of .wrap div?) turns black when resizing on Chrome on Windows 8.1 and Chromium on Ubuntu

### ISSUE THREAD

**Issue by jimlavrenz** [poole/lanyon#81]
Background turns black on complete webpage when re-sizing left to right or right to left.  Goes from white to black then stays black for a bit and turns white if you resize more.  May transition several times during the course of re-sizing from most wide to most narrow.  If you resize too rapidly, however, you might not see it happen.

To fix this I added the following two lines to the first occurrence of the `.wrap` class in the lanyon.css file (line 63 in my lanyon.css file),
  **height: 100%;**
  **background-color: white !important;**

Without the _height:100%;_ there was still black on the very bottom.  Putting a default in the body/html section of *background-color: white !important;* didn't do it, so I made the `.wrap` div 100% in height as a hack and left the body and html section alone.

You can see the behavior on [Lanyon demo](http://lanyon.getpoole.com) on Windows 8.1 using the latest Chrome browser or using Ubuntu 14.04.1 using the latest Chromium browser.  Doesn't occur on OSX (10.10.1) at all regardless of browser used.

The image below on the left shows the issue in Chromium on Ubuntu within a VM hosted on Windows.  The right part of the image is Chrome on the actual Windows host machine.  I screen grabbed from the Windows 8.1 host (this is one screen grab that shows the issue on both browsers and operating systems).  **To my understanding,** Chromium is the open source code base of Chrome.  Google then adds some tracking stuff and brands it Chrome.

![lanyon_screen_grab](https://cloud.githubusercontent.com/assets/8029513/5504130/3463f362-8745-11e4-97a8-cdf1db148212.png)

**Comment by SeverinDK** [comment]
I am having this exact problem, but I am not using lanyon. I hope Chrome finds a solution for this. Don't want to hackfix it.
![chromeblack](https://cloud.githubusercontent.com/assets/1542119/5723434/47319356-9b44-11e4-9e8f-266ef8ad89ae.jpg)

**Comment by jimlavrenz** [comment]
I admit hacks are ugly.  I'll close this out -- assuming I can as I opened the issue -- now that I know it is a Chrome thing.  Someone can always check the closed issue list if they run into this and want the hack.
Thanks!
