### ISSUE TITLE
tags or categories on posts?

### ISSUE THREAD

**Issue by georgiamoon** [poole/lanyon#83]
What's the best way to make it so that posts can have tags or categories? I'd love to have a layout that was a post listing based on a tag/category.

**Comment by wireddown** [comment]
I have a working demo for tags here:

https://github.com/wireddown/wireddown.github.io/tree/feature_tags

**Comment by wireddown** [comment]
I've opened [PR 85](https://github.com/poole/lanyon/pull/85) to add tags.

**Comment by trevordmiller** [comment]
@mdo I would love to see a recommended way of implementing tags and/or categories as well.

_p.s. poole and lanyon are awesome! Just started a new blog with them and am loving it ;) Thank you!_

**Comment by mdo** [comment]
Punting on tags and categories, per #85.
