### ISSUE TITLE
How do I stop the page from jumping in landscape mode for iPhone 6?

### ISSUE THREAD

**Issue by antonioOrtiz** [poole/lanyon#86]
I am using the lanyon jekyll theme and I discovered the page begins to jump up and down  when viewing it with a iPhone 6 in landscape mode.

 
(This occurred on the site I was creating, but it also happens if you go right to the demo [page][1]).

Using the first viewport tag, causes the issue, the second one fixes it but it's zoomed in a tad.

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="viewport" content="width=device-width">

Is there a way to make this normal?

  [1]: https://www.dropbox.com/s/76fbajih0fwtt0k/MOV_0134.MOV.mov?dl=0

**Comment by xaprb** [comment]
Readers of my blog are complaining about this as well. I don't know much about responsive design so I feel a little helpless to figure out how to solve this.

**Comment by antonioOrtiz** [comment]
After some troubleshooting, it turns out I should have said the meta tag (at this point ) is just a variable in the equation which varies the degree of "jankyness."  I went through the css, and if you go to the `poole.css` file:

    @media (min-width: 38rem) {
        html {
        font-size: 20px;
        }
    }

and comment it out, it'll stop the jumping. Didn't have time to test it an exhaustive fashion, but for now it appears to work.

**Comment by mdo** [comment]
This was solved in the latest code, but not in the demo site. Will be fixed soon.

**Comment by xaprb** [comment]
Is there a specific diff you can point to so I can patch my site that's
based on lanyon (but doesn't use it verbatim) ?

**Comment by mdo** [comment]
Easiest fix that I recall is changing all `rem` units to `em`s in the media query dimensions.
