### ISSUE TITLE
Load homepage with sidebar open?

### ISSUE THREAD

**Issue by fps-vogel** [poole/lanyon#87]
Is there a way to have the sidebar open by default, but only on the homepage?

**Comment by mdo** [comment]
Not built in, no. You'd have to conditionally set the hidden checkbox to `checked` for just the homepage. Something like the following would work:

```
<input type="checkbox" {% if page.title == "home" %}checked{% end %}>
```

**Comment by fps-vogel** [comment]
Thanks, mdo. But I'm getting a page build error. I'm putting it at the top of sidebar.html before I push to GitHub. Is that wrong?

**Comment by mdo** [comment]
Sorry, I should've clarified—I meant something *like* that code snippet would work. I didn't test it in my haste. In the sidebar include, change the following:

```
<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox">
```

to...

```
<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox" {% if page.title =="Home" %}checked{% endif %}>
```

That should do it.

**Comment by fps-vogel** [comment]
Perfect, thanks!
