### ISSUE TITLE
Jumpy sidebar

### ISSUE THREAD

**Issue by travs** [poole/lanyon#88]
There seem to be a couple issues with the sidebar but I didn't see this one reported yet.

When I click the sandwich button to toggle the sidebar, the viewing area *jumps* out instead of sliding. And when I click the put the sidebar away, the sandwich button jumps behind the sidebar before it closes, again instead of sliding.

Anyone have a similar experience?

GIF: First, correct sliding; second, jumpy siding.
![lanyon](https://cloud.githubusercontent.com/assets/7369273/5778191/0f21131a-9d74-11e4-8555-d0d09b580c14.gif)

**Comment by afhaque** [comment]
Yeah. I'm seeing a similar issue... wasn't sure if it was because I am A) Running jekyll on windows or B) Running locally.

**Comment by x43x61x69** [comment]
A quick dirty fix to this could be add:

**z-index: 100;**

to 

**.sidebar { }**

**Comment by mdo** [comment]
Without looking at the markup, I can't tell you much. I'd assume something's out of sync with the default theme and it's implementation or customization on your end. Holler if it's still an issue after snagging the latest code from here.
